import type { GalleryItem } from "@/lib/types";

export const galleryItems: GalleryItem[] = [
  {
    slug: "studying",
    artist: "Tommy Dadmun",
    title: "Studying",
    album: "Axiom",
    year: 2008,
    key: { estimated: "A minor", confidence: 0.659 },
    tempo: { bpm: 184.6 },
    duration: 176.03,
    dominantPitches: ["C", "A", "Db"],
    sectionCount: 10,
    vocalPresencePct: 16.8,
    dynamicRangeDb: 5.7,
    climaxPct: 85,
    a4Hz: 440.51,
    sampleRate: 22050,
    prose: "Warm coral and spring green bands divide the pitch content almost equally, shifting constantly across ten distinct sections. The emotional peak arrives past the one-third mark while the volume peak waits until the final sixth, leaving a ninety-second gap where tension dissolves before loudness arrives. Deep magenta spike clusters ground the rhythm in bass weight. Vocal fragments appear briefly in every section, threading continuously through the instrumental texture without ever claiming extended territory.",
  },
  {
    slug: "axiom",
    artist: "Tommy Dadmun",
    title: "Axiom",
    album: "Axiom",
    year: 2008,
    key: { estimated: "A minor", confidence: 0.919 },
    tempo: { bpm: 76.0 },
    duration: 236.1,
    dominantPitches: ["A", "C", "E"],
    sectionCount: 9,
    vocalPresencePct: 14.0,
    dynamicRangeDb: 5.1,
    climaxPct: 41,
    a4Hz: 441.02,
    sampleRate: 22050,
    prose: "Nearly half the percussive energy concentrates in deep violet bass clusters, while spring green and warm coral bands drift through rings compressed into just 5 decibels. The loudest moment lands at 40% through, but harmonic tension peaks in the final section, creating an arc where volume recedes as strain intensifies. The vocal melody appears briefly in every section, never absent for more than seven seconds, weaving a continuous thread through a structure that ranges from five-second fragments to a full minute of sustained contemplation.",
  },
  {
    slug: "no-disclaimers",
    artist: "Tommy Dadmun",
    title: "No Disclaimers",
    album: "Axiom",
    year: 2008,
    key: { estimated: "F major", confidence: 0.778 },
    tempo: { bpm: 73.8 },
    duration: 276.97,
    dominantPitches: ["C", "D", "A"],
    sectionCount: 8,
    vocalPresencePct: 14.0,
    dynamicRangeDb: 7.7,
    climaxPct: 74,
    a4Hz: 440.25,
    sampleRate: 22050,
    prose: "Deep blue bass spikes cluster toward the center beneath warm coral and gold-green bands showing C and D as dominant pitch classes. Emotional tension peaks at one-third through, but the volume surge waits until three-quarters complete, so the strain resolves first, then the power arrives. A white vocal thread appears in brief bursts across every section, comprising only 14% of the song. The rings drift moderately from center as the harmony moves between tonic stability and chromatic exploration.",
  },
  {
    slug: "plane-to-heaven",
    artist: "Tommy Dadmun",
    title: "Plane to Heaven",
    album: "Axiom",
    year: 2008,
    key: { estimated: "D major", confidence: 0.736 },
    tempo: { bpm: 76.0 },
    duration: 165.91,
    dominantPitches: ["A", "D", "C"],
    sectionCount: 9,
    vocalPresencePct: 26.6,
    dynamicRangeDb: 6.7,
    climaxPct: 87,
    a4Hz: 441.27,
    sampleRate: 22050,
    prose: "Compressed within a tight 6.7 dB dynamic range, every percussive detail bristles at the ring edges while deep violet bass clusters claim nearly half the rhythmic weight. Nine sections vary dramatically, from a brief 7-second fragment to one 38-second passage dominating the center. Spring green commands over twenty percent of the harmonic content. The loudest peak holds until the final third, so the climax must be reached, not simply encountered. Vocals thread briefly through the dense rhythmic texture that defines the bristling perimeter.",
  },
  {
    slug: "lovely",
    artist: "Tommy Dadmun",
    title: "Lovely",
    album: "Axiom",
    year: 2008,
    key: { estimated: "G major", confidence: 0.849 },
    tempo: { bpm: 61.5 },
    duration: 222.65,
    dominantPitches: ["G", "D", "A"],
    sectionCount: 8,
    vocalPresencePct: 26.5,
    dynamicRangeDb: 5.6,
    climaxPct: 46,
    a4Hz: 440.51,
    sampleRate: 22050,
    prose: "Eight uneven sections stretch from brief ten-second fragments to extended passages over forty seconds. Amber bands claim over twenty percent of the pitch content while deep violet percussion clusters ground the composition's wide nineteen-semitone vocal range. The emotional peak blazes at just over halfway through, yet maximum volume arrives nearly fifty seconds later, so the loudest moment feels like gentle resolution settling over prior intensity. The compressed 5.6 dB range allows the song's complexity to unfold through color and spacing.",
  },
  {
    slug: "she-waits",
    artist: "Tommy Dadmun",
    title: "She Waits",
    album: "Axiom",
    year: 2008,
    key: { estimated: "A minor", confidence: 0.581 },
    tempo: { bpm: 66.3 },
    duration: 213.09,
    dominantPitches: ["E", "D", "F"],
    sectionCount: 10,
    vocalPresencePct: 11.8,
    dynamicRangeDb: 4.9,
    climaxPct: 47,
    a4Hz: 442.04,
    sampleRate: 22050,
    prose: "Jade and gold-green bands claim the largest visual territories as nine pitch classes sprawl across the harmonic landscape. The emotional peak blazes at just 16% through, but volume waits until 47%, so psychological intensity builds and dissipates long before sonic weight materializes. Ten sections create dramatic contrasts, from fleeting 4-second fragments to one sprawling 67-second passage. The compressed 4.9 dB range ensures every harmonic shift registers at nearly identical visual thickness.",
  },
  {
    slug: "thin-line-sunrise",
    artist: "Tommy Dadmun",
    title: "Thin Line Sunrise",
    album: "Axiom",
    year: 2008,
    key: { estimated: "C major", confidence: 0.872 },
    tempo: { bpm: 73.8 },
    duration: 199.18,
    dominantPitches: ["C", "D", "A"],
    sectionCount: 8,
    vocalPresencePct: 26.4,
    dynamicRangeDb: 7.1,
    climaxPct: 82,
    a4Hz: 441.78,
    sampleRate: 22050,
    prose: "Warm coral bands dominate nearly a quarter of the harmonic landscape, anchoring each ring while gold-green threads weave through at 14%. Deep indigo bass clusters claim nearly half the rhythmic energy, dense spikes grounding the composition's momentum. Eight sections stretch from a brief 7-second fragment to an extended 56-second passage. Emotional tension crests in the second half, yet the volume peak waits another 28 seconds, so the climax builds through harmonic intensity before sonic weight arrives.",
  },
];
