import type { GalleryItem } from "@/lib/types";

export const galleryItems: GalleryItem[] = [
  {
    slug: "studying",
    artist: "Tommy Dadmun",
    title: "Studying",
    album: "Axiom",
    year: 2008,
    key: { estimated: "A minor", confidence: 0.659 },
    tempo: { bpm: 184.6 },
    duration: 176.03,
    dominantPitches: ["C", "A", "Db"],
    sectionCount: 10,
    vocalPresencePct: 16.8,
    dynamicRangeDb: 5.7,
    climaxPct: 85,
    a4Hz: 440.51,
    sampleRate: 22050,
    prose: "The Prism Ring\u2019s nearly balanced warm coral and spring green bands reveal C and A as co-dominant pitch classes, each claiming about 17% of the harmonic space and creating a tonal ambiguity that resists clear key resolution. Harmonic tension peaks dramatically at the one-third mark while the volume climax delays until 85% through the composition, meaning the emotional strain resolves long before the sonic intensity peaks and robs the finale of dramatic surprise. The sparse silk thread appears in only 17% of the track, leaving vast instrumental stretches punctuated by brief vocal moments that feel more like textural accents than melodic anchors. Bass-heavy spike clusters dominate the percussive landscape with nearly half the transient energy concentrated in the low frequencies, giving the rhythm section a foundation-focused weight that grounds the floating harmonies.",
  },
  {
    slug: "axiom",
    artist: "Tommy Dadmun",
    title: "Axiom",
    album: "Axiom",
    year: 2008,
    key: { estimated: "A minor", confidence: 0.919 },
    tempo: { bpm: 76.0 },
    duration: 236.1,
    dominantPitches: ["A", "C", "E"],
    sectionCount: 9,
    vocalPresencePct: 14.0,
    dynamicRangeDb: 5.1,
    climaxPct: 41,
    a4Hz: 441.02,
    sampleRate: 22050,
    prose: "The Prism Ring displays spring green and warm coral as its most prominent color bands, reflecting the dominance of A and C pitch classes that anchor the harmonic structure throughout the composition. A section gap appears at 2:15, dividing the nine-section structure and creating a clear visual break that corresponds to a major compositional boundary. The song\u2019s harmonic tension reaches its peak near the end while the loudness climaxes much earlier in the middle, creating a sense of mounting unease that builds long after the volume has already receded. Heavy compression limits the dynamic range to just 5.1 decibels, forcing all sonic elements into a narrow loudness band that makes the bass-dominant spike clusters (45% low-frequency energy) compete directly with the sparse vocal appearances that occupy only 14% of the track\u2019s duration.",
  },
  {
    slug: "no-disclaimers",
    artist: "Tommy Dadmun",
    title: "No Disclaimers",
    album: "Axiom",
    year: 2008,
    key: { estimated: "F major", confidence: 0.778 },
    tempo: { bpm: 73.8 },
    duration: 276.97,
    dominantPitches: ["C", "D", "A"],
    sectionCount: 8,
    vocalPresencePct: 14.0,
    dynamicRangeDb: 7.7,
    climaxPct: 74,
    a4Hz: 440.25,
    sampleRate: 22050,
    prose: "The Prism Ring displays warm coral and gold-green as its dominant color bands, reflecting C and D as the most prominent pitch classes throughout the composition. Harmonic tension reaches its peak at just over a quarter through the song while maximum volume doesn\u2019t arrive until three-quarters complete, creating a structural arc where emotional intensity precedes and outlasts the dynamic climax. The silk thread appears in only 14% of the composition with its strongest presence concentrated in the seventh section, making vocal moments feel like brief emergences from a largely instrumental landscape. Eight section gaps divide the sonicture into irregular segments, with a prominent structural boundary occurring at 1:07 that marks a significant shift in the composition\u2019s organization. Bass-heavy spike clusters dominate the percussive texture, giving the rhythmic foundation a substantial low-end emphasis that anchors the harmonic movement above.",
  },
  {
    slug: "plane-to-heaven",
    artist: "Tommy Dadmun",
    title: "Plane to Heaven",
    album: "Axiom",
    year: 2008,
    key: { estimated: "D major", confidence: 0.736 },
    tempo: { bpm: 76.0 },
    duration: 165.91,
    dominantPitches: ["A", "D", "C"],
    sectionCount: 9,
    vocalPresencePct: 26.6,
    dynamicRangeDb: 6.7,
    climaxPct: 87,
    a4Hz: 441.27,
    sampleRate: 22050,
    prose: "The Prism Ring displays spring green and gold-green as its most prominent color bands, reflecting the song\u2019s emphasis on A and D pitch classes that account for over a third of the harmonic content, establishing a foundation that pulls the ear toward familiar territory even as complexity builds around it. Nine distinct section gaps break the composition into irregular fragments at points like the 0:59 boundary, creating a stop-start momentum that mirrors the song\u2019s syncopated rhythmic density of 1.72 times normal pacing, where each expected beat spawns additional percussive events that thicken the texture without obscuring the pulse. The spike clusters show bass-heavy energy distribution with gold spikes dominating over white and ice-blue equivalents, anchoring the rhythmic complexity in low-frequency percussion that provides stability beneath the fragmented structure. The song\u2019s compressed 6.7 dB dynamic range maintains consistent intensity throughout most of its length before delivering its loudest moment at 87% completion, denying the typical arc of tension and release in favor of sustained engagement that makes the final peak feel like an emphatic statement rather than a climactic arrival.",
  },
  {
    slug: "lovely",
    artist: "Tommy Dadmun",
    title: "Lovely",
    album: "Axiom",
    year: 2008,
    key: { estimated: "G major", confidence: 0.849 },
    tempo: { bpm: 61.5 },
    duration: 222.65,
    dominantPitches: ["G", "D", "A"],
    sectionCount: 8,
    vocalPresencePct: 26.5,
    dynamicRangeDb: 5.6,
    climaxPct: 46,
    a4Hz: 440.51,
    sampleRate: 22050,
    prose: "The Prism bands display amber and gold-green as the strongest color signatures, reflecting G and D as the most prominent pitch classes throughout the composition. A section gap appears at the 45-second mark, dividing the sonicture into eight irregular segments that create visual punctuation points across the circular structure. The song\u2019s compressed 5.6 dB dynamic range produces consistently thick rings with minimal thickness variation, while harmonic tension peaks much later than the loudest moments, creating a delayed sense of musical climax that arrives well after the volume has already begun to recede. Bass-heavy spike clusters dominate the percussion texture with over half the transient energy concentrated in the gold frequency band, giving the rhythmic foundation a kick-driven character. The vocal melody spans an unusually wide 19-semitone range, causing the silk thread to trace dramatic vertical movements that stretch from deep bass registers to high soprano territory, amplifying the sense of vocal athleticism and emotional range.",
  },
];
